INSERT INTO [dbo].[product] ([id], [name]) VALUES (1, N'продукт 1')
INSERT INTO [dbo].[product] ([id], [name]) VALUES (2, N'продукт 2')
INSERT INTO [dbo].[product] ([id], [name]) VALUES (3, N'продукт 3')
INSERT INTO [dbo].[product] ([id], [name]) VALUES (4, N'продукт 4')
INSERT INTO [dbo].[product] ([id], [name]) VALUES (5, N'кродукт 5')
